/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI } from './js-genai.js';
import { getAllFrameOrigins } from './utils.js';
import * as Transcript from './transcript.js';

const statusDiv = document.getElementById('status');
const tbody = document.getElementById('tableBody');
const thead = document.getElementById('tableHeaderRow');
const copyToClipboard = document.getElementById('copyToClipboard');
const copyAsScriptToolConfig = document.getElementById('copyAsScriptToolConfig');
const copyAsJSON = document.getElementById('copyAsJSON');
const toolNames = document.getElementById('toolNames');
const chips = document.getElementById('chips');
const inputArgsText = document.getElementById('inputArgsText');
const executeBtn = document.getElementById('executeBtn');
const toolResults = document.getElementById('toolResults');
const userPromptText = document.getElementById('userPromptText');
const promptBtn = document.getElementById('promptBtn');
const traceBtn = document.getElementById('traceBtn');
const resetBtn = document.getElementById('resetBtn');
const apiKeyBtn = document.getElementById('apiKeyBtn');
const advancedSection = document.getElementById('advancedSection');
const suggestUserPromptCheckbox = document.getElementById('suggestUserPromptCheckbox');

Transcript.mount(document.getElementById('transcript'));

// First, request list of tools from content script living in top-level frame.
(async () => {
  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    const fromOrigins = await getAllFrameOrigins(tab.id);
    await chrome.tabs.sendMessage(tab.id, { action: 'LIST_TOOLS', fromOrigins }, { frameId: 0 });
  } catch (error) {
    const statusDiv = document.getElementById('status');
    statusDiv.textContent = error;
    statusDiv.hidden = false;
    copyToClipboard.hidden = true;
  }
})();

// Never undefined: a tool-response turn builds getConfig() from this, and a
// navigation mid-run delivers a message with no tools. See the guard below.
let currentTools = [];

let userPromptPendingId = 0;
let lastSuggestedUserPrompt = '';

// Listen for the results coming back from content.js
chrome.runtime.onMessage.addListener(async ({ message, tools, url, type }, sender) => {
  // Internal signals (e.g. contentScriptReady) are handled elsewhere.
  if (type) return;
  if (sender.frameId && sender.frameId !== 0) return;

  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (sender.tab && sender.tab.id !== tab.id) return;

  tbody.innerHTML = '';
  thead.innerHTML = '';
  toolNames.innerHTML = '';

  statusDiv.textContent = message;
  statusDiv.hidden = !message;

  const haveNewTools = JSON.stringify(currentTools) !== JSON.stringify(tools);

  currentTools = tools ?? [];

  if (!tools || tools.length === 0) {
    const row = document.createElement('tr');
    row.innerHTML = `<td colspan="100%"><i>No tools registered yet in ${url || tab.url}</i></td>`;
    tbody.appendChild(row);
    inputArgsText.value = '';
    inputArgsText.disabled = true;
    toolNames.disabled = true;
    executeBtn.disabled = true;
    copyToClipboard.hidden = true;
    return;
  }

  inputArgsText.disabled = false;
  toolNames.disabled = false;
  executeBtn.disabled = false;
  copyToClipboard.hidden = false;

  const KEYS = ['description', 'inputSchema', 'readOnlyHint', 'untrustedContentHint', 'name'];
  const keys = KEYS.filter((key) => tools.some((tool) => key in tool));
  keys.forEach((key) => {
    const th = document.createElement('th');
    th.textContent = key;
    thead.appendChild(th);
  });

  tools.forEach((item) => {
    const row = document.createElement('tr');
    keys.forEach((key) => {
      const td = document.createElement('td');
      const pre = document.createElement('pre');
      try {
        pre.textContent = JSON.stringify(JSON.parse(item[key]), '', '  ');
        td.appendChild(pre);
      } catch (error) {
        // `?? ''` because an absent hint arrives as the key present with an
        // undefined value (content.js), and textContent stringifies undefined
        // to the literal "undefined" — noise in a table whose job is showing
        // exactly what the page declared. Blank means undeclared.
        td.textContent = item[key] ?? '';
      }
      row.appendChild(td);
    });
    tbody.appendChild(row);

    const option = document.createElement('option');
    option.textContent = `"${item.name}"${item.frameId !== 0 ? ` (${item.frameId})` : ''}`;
    option.value = item.name;
    option.dataset.inputSchema = item.inputSchema || '{}';
    option.dataset.frameId = item.frameId;
    toolNames.appendChild(option);
  });
  updateDefaultValueForInputArgs();
  renderChips(tools);

  if (haveNewTools) suggestUserPrompt();
});

/**
 * Opener chips (issue 0005): one per registered tool, derived deterministically
 * from the tool list — never generated by the model.
 *
 * They double as a live readout of what the agent can reach on this page, so a
 * missing chip is a registration bug you can see before typing anything.
 * Clicking one only populates the composer; nothing is executed.
 */
function renderChips(tools) {
  chips.textContent = '';
  for (const tool of tools ?? []) {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = isDestructive(tool) ? 'chip dstr' : 'chip';
    chip.textContent = isDestructive(tool) ? `❗ ${tool.name}` : tool.name;
    chip.title = tool.description ?? tool.name;
    chip.dataset.tool = tool.name;
    chip.addEventListener('click', () => {
      userPromptText.value = `Use ${tool.name} on this page.`;
      userPromptText.focus();
    });
    chips.appendChild(chip);
  }
}

tbody.ondblclick = () => {
  tbody.classList.toggle('prettify');
};

copyAsScriptToolConfig.onclick = async () => {
  const text = currentTools
    .map((tool) => {
      return `\
script_tools {
  name: ${JSON.stringify(tool.name)}
  description: ${JSON.stringify(tool.description || '')}
  input_schema: ${JSON.stringify(tool.inputSchema || { type: 'object', properties: {} })}
}`;
    })
    .join('\r\n');
  await navigator.clipboard.writeText(text);
};

copyAsJSON.onclick = async () => {
  const tools = currentTools.map((tool) => {
    return {
      name: tool.name,
      description: tool.description,
      inputSchema: tool.inputSchema
        ? JSON.parse(tool.inputSchema)
        : { type: 'object', properties: {} },
    };
  });
  await navigator.clipboard.writeText(JSON.stringify(tools, '', '  '));
};

// Interact with the page

let genAI, chat;

async function initGenAI() {
  let env;
  try {
    // Try load .env.json if present.
    env = (await import('./.env.json', { with: { type: 'json' } })).default;
  } catch {}
  if (env?.apiKey) localStorage.apiKey ??= env.apiKey;
  if (localStorage.model === 'gemini-2.5-flash') {
    localStorage.model = 'gemini-3-flash-preview';
  }
  if (localStorage.model === 'gemini-3.1-flash-lite-preview') {
    localStorage.model = 'gemini-3.1-flash-lite';
  }
  localStorage.model ??= env?.model || 'gemini-3.6-flash';
  genAI = localStorage.apiKey ? new GoogleGenAI({ apiKey: localStorage.apiKey }) : undefined;
  promptBtn.disabled = !localStorage.apiKey;
  resetBtn.disabled = !localStorage.apiKey;
  apiKeyBtn.textContent = localStorage.apiKey ? 'Update Gemini API key' : 'Set Gemini API key';

  suggestUserPromptCheckbox.checked = localStorage.suggestUserPrompt !== 'false';
}
await initGenAI();

document.querySelectorAll('input[name="model"]').forEach((radio) => {
  radio.checked = radio.value === localStorage.model;
  radio.onclick = () => {
    localStorage.model = radio.value;
    chat = undefined;
    advancedSection.hidePopover();
  };
});

suggestUserPromptCheckbox.onchange = () => {
  localStorage.suggestUserPrompt = suggestUserPromptCheckbox.checked;
  if (localStorage.suggestUserPrompt) suggestUserPrompt();
  advancedSection.hidePopover();
};

async function suggestUserPrompt() {
  if (localStorage.suggestUserPrompt === 'false') return;
  // `?.` guards an upstream crash, not a hypothetical: `currentTools` starts
  // undefined and stays undefined until the first tool-list message lands, but
  // Reset, the API-key prompt and the suggest checkbox all call this
  // immediately. Any of them before the first message threw an uncaught
  // TypeError in the panel. Intermittent, ~1 run in 14, and it tripped this
  // project's own "no console errors" gate.
  if (!currentTools?.length || !genAI || userPromptText.value !== lastSuggestedUserPrompt)
    return;
  const userPromptId = ++userPromptPendingId;
  const response = await genAI.models.generateContent({
    model: localStorage.model,
    contents: [
      '**Context:**',
      `Today's date is: ${getFormattedDate()}`,
      '**Tool Rules:**',
      '1. **Bank Transaction Filter:** Use **PAST** dates only (e.g., "last month," "December 15th," "yesterday").',
      '2. **Flight Search:** Use **FUTURE** dates only (e.g., "next week," "February 15th").',
      '3. **Accommodation Search:** Use **FUTURE** dates only (e.g., "next weekend," "March 15th").',
      '**Task:**',
      'Generate one natural user query for a range of tools below, ideally chaining them together.',
      'Ensure the date makes sense relative to today.',
      'Output the query text only.',
      '**Tools:**',
      JSON.stringify(currentTools),
    ],
  });
  if (userPromptId !== userPromptPendingId || userPromptText.value !== lastSuggestedUserPrompt)
    return;
  lastSuggestedUserPrompt = response.text;
  userPromptText.value = '';
  for (const chunk of response.text) {
    await new Promise((r) => requestAnimationFrame(r));
    userPromptText.value += chunk;
  }
}

userPromptText.onkeydown = (event) => {
  if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) {
    event.preventDefault();
    promptBtn.click();
  }
};

promptBtn.onclick = async () => {
  try {
    await promptAI();
  } catch (error) {
    trace.push({ error });
    logPrompt('error', { text: `Error: "${error}"` });
  }
};

let trace = [];

async function promptAI() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

  chat ??= genAI.chats.create({ model: localStorage.model });

  const message = userPromptText.value;
  userPromptText.value = '';
  lastSuggestedUserPrompt = '';
  logPrompt('user', { text: message });
  const sendMessageParams = { message, config: getConfig() };
  trace.push({ userPrompt: sendMessageParams });
  let currentResult = await chat.sendMessage(sendMessageParams);
  let finalResponseGiven = false;

  while (!finalResponseGiven) {
    const response = currentResult;
    trace.push({ response });
    const functionCalls = response.functionCalls || [];

    if (functionCalls.length === 0) {
      if (!response.text) {
        logPrompt('warning', { text: `AI response has no text: ${JSON.stringify(response.candidates)}` });
      } else {
        logPrompt('assistant', { text: response.text?.trim() });
      }
      finalResponseGiven = true;
    } else {
      const toolResponses = [];
      for (const { name: toolName, args } of functionCalls) {
        let [frameId, name] = toolName.split(/_(.*)/s)[1].split(/_(.*)/s);
        frameId = parseInt(frameId);
        const inputArgs = JSON.stringify(args);
        const declared = currentTools?.find((t) => t.name === name);
        const toolEvent = logPrompt('toolCall', {
          toolName: name,
          frameId,
          inputSchema: declared?.inputSchema,
          destructive: isDestructive(declared),
          proposedArgs: args,
          sentArgs: args,
        });
        // Issue 0002: page URL either side of the call. Sidebar-side only —
        // content.js is not involved, we already hold tab.id here.
        const urlBefore = await tabUrl(tab.id);
        const startedAt = Date.now();
        try {
          const result = await executeTool(tab.id, name, inputArgs, frameId);
          toolResponses.push({ functionResponse: { name: toolName, response: { result } } });
          logPrompt(toolEvent, {
            status: 'ok',
            result,
            urlBefore,
            urlAfter: await tabUrl(tab.id),
            durationMs: Date.now() - startedAt,
          });
        } catch (e) {
          const urlAfter = await tabUrl(tab.id);
          // A call whose result was destroyed by navigation DID run, and may have
          // had side effects. Reporting it as `error` reads as "nothing happened",
          // which is the opposite of the truth. See context.md#Lost result.
          const status = isLostToNavigation(e) ? 'lost' : 'error';
          logPrompt(toolEvent, {
            status,
            errorMessage: e.message,
            urlBefore,
            urlAfter,
            durationMs: Date.now() - startedAt,
          });
          toolResponses.push({
            functionResponse: { name: toolName, response: { error: e.message } },
          });
        }
      }

      const sendMessageParams = { message: toolResponses, config: getConfig() };
      trace.push({ userPrompt: sendMessageParams });
      currentResult = await chat.sendMessage(sendMessageParams);
    }
  }
}

resetBtn.onclick = () => {
  chat = undefined;
  trace = [];
  userPromptText.value = '';
  lastSuggestedUserPrompt = '';
  Transcript.reset();
  suggestUserPrompt();
};

apiKeyBtn.onclick = async () => {
  const apiKey = prompt('Enter Gemini API key', localStorage.apiKey);
  if (apiKey == null) return;
  localStorage.apiKey = apiKey;
  await initGenAI();
  suggestUserPrompt();
};

traceBtn.onclick = async () => {
  const text = JSON.stringify(trace, '', ' ');
  await navigator.clipboard.writeText(text);
};

executeBtn.onclick = async () => {
  toolResults.textContent = '';
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  const name = toolNames.selectedOptions[0].value;
  const inputArgs = inputArgsText.value;
  const frameId = parseInt(toolNames.selectedOptions[0].dataset.frameId);
  toolResults.textContent = await executeTool(tab.id, name, inputArgs, frameId).catch(
    (error) => `⚠️ Error: "${error}"`,
  );
};

async function executeTool(tabId, name, inputArgs, frameId) {
  let toolsReady;
  const toolsPromise = new Promise((resolve) => {
    toolsReady = resolve;
  });

  let targetTabId = tabId;
  let contentScriptReadyResolve;
  const contentScriptReadyPromise = new Promise((r) => { contentScriptReadyResolve = r; });

  const listener = (msg, sender) => {
    if (msg.type === 'contentScriptReady' && sender.tab) {
      if (sender.tab.id === tabId || sender.tab.openerTabId === tabId) {
        targetTabId = sender.tab.id;
        contentScriptReadyResolve();
      }
    }
    if (msg.tools && sender.tab?.id === targetTabId) {
      toolsReady();
    }
  };
  chrome.runtime.onMessage.addListener(listener);

  try {
    try {
      const result = await chrome.tabs.sendMessage(
        tabId,
        { action: 'EXECUTE_TOOL', name, inputArgs },
        { frameId },
      );
      if (result !== null) return result;
    } catch (error) {
      if (!/message channel (is )?closed/.test(error.message)) throw error;
    }

    // A navigation was triggered. The result will be on the next document,
    // which may live in a new tab if the tool opened one.
    await Promise.race([
      contentScriptReadyPromise,
      new Promise((r) => setTimeout(r, 2000)),
    ]);

    await Promise.race([
      toolsPromise,
      new Promise((r) => setTimeout(r, 2000)),
    ]);

    await waitForPageLoad(targetTabId);

    return await chrome.tabs.sendMessage(
      targetTabId,
      { action: 'GET_CROSS_DOCUMENT_SCRIPT_TOOL_RESULT' },
      // The original frameId only makes sense in the original tab.
      { frameId: targetTabId === tabId ? frameId : 0 },
    );
  } finally {
    chrome.runtime.onMessage.removeListener(listener);
  }
}

toolNames.onchange = updateDefaultValueForInputArgs;

function updateDefaultValueForInputArgs() {
  const inputSchema = toolNames.selectedOptions[0].dataset.inputSchema || '{}';
  const template = generateTemplateFromSchema(JSON.parse(inputSchema));
  inputArgsText.value = JSON.stringify(template, '', ' ');
}

// Utils

// The seam (context.md#The seam): all Event emission happens here. A string
// first argument creates a new Event of that kind; passing back the Event
// returned from an earlier call updates it in place instead — that's how the
// "calling tool" and "result"/"error" call sites end up as one Event.
function logPrompt(kindOrEvent, data) {
  return typeof kindOrEvent === 'string'
    ? Transcript.append(kindOrEvent, data)
    : Transcript.update(kindOrEvent, data);
}

/** Current URL of a tab, or undefined if it can't be read. Never throws. */
async function tabUrl(tabId) {
  try {
    return (await chrome.tabs.get(tabId))?.url;
  } catch {
    return undefined;
  }
}

/**
 * Did this failure destroy the tool's result rather than the tool's action?
 *
 * Matched narrowly and deliberately. Upstream ALREADY recovers results across
 * script navigation, form navigation and new-tab handoff — the e2e suite proves
 * it with four passing assertions — and those calls resolve rather than throwing,
 * so they never reach here. Broadening this test would reclassify working
 * behaviour as `lost`, which is a regression, not a feature.
 */
function isLostToNavigation(error) {
  return /cannot return tool results after a cross-origin navigation/i.test(
    String(error?.message ?? error),
  );
}

/**
 * Does this tool have outward-facing side effects?
 *
 * Precedence, highest first:
 *   1. `readOnlyHint: true` — authoritative. A tool the page declares read-only
 *      is never destructive, whatever it's called.
 *   2. The name heuristic (context.md#Destructive tool).
 *
 * `destructiveHint` is NOT consulted, and cannot be: the Chrome Origin Trial
 * puts exactly two keys on `annotations` — `readOnlyHint` and
 * `untrustedContentHint` — so a page that correctly declares
 * `destructiveHint: true` is invisible to any extension, ours included. Measured
 * against a fixture that declares it, not assumed; the e2e suite carries a
 * canary that goes red the day Chrome adds the field. See
 * docs/adr/0004-forward-destructive-hint.md for the attempt and the revert.
 *
 * Consequence to be honest about: annotations can CLEAR a tool but not FLAG one.
 */
function isDestructive(tool) {
  if (tool?.readOnlyHint) return false;
  // Separator-agnostic: real tools use hyphens (optimizely-…-submit) and the
  // fixtures use underscores (submit_order). Both must match.
  return /(^|[-_])(submit|delete|purchase)([-_]|$)/i.test(tool?.name ?? '');
}

function getFormattedDate() {
  const today = new Date();
  return today.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function getConfig() {
  const systemInstruction = [
    'You are an assistant embedded in a browser tab.',
    'User prompts typically refer to the current tab unless stated otherwise.',
    'Use the provided tools to query page content when you need it.',
    `Today's date is: ${getFormattedDate()}`,
    'CRITICAL RULE: Whenever the user provides a relative date (e.g., "next Monday", "tomorrow", "in 3 days"),  you must calculate the exact calendar date based on today\'s date.',
    'CRITICAL RULE: Do not try to use other tools than the available ones.',
  ];

  // `?? []` guards the same upstream crash the `?.` at the toolCall lookup
  // does. A tool that navigates the page (e.g. a search-results tool) kills the
  // content script AND delivers a tool-less message, so the tool-response turn
  // that follows built its config from an undefined list and threw
  // "Cannot read properties of undefined (reading 'map')" — after the tool
  // error itself had already been handled cleanly.
  const functionDeclarations = (currentTools ?? []).map((tool) => {
    return {
      name: `_${tool.frameId}_${tool.name}`,
      description: tool.description,
      parametersJsonSchema: tool.inputSchema
        ? JSON.parse(tool.inputSchema)
        : { type: 'object', properties: {} },
    };
  });
  return { systemInstruction, tools: [{ functionDeclarations }] };
}

function generateTemplateFromSchema(schema) {
  if (!schema || typeof schema !== 'object') {
    return null;
  }

  if (schema.hasOwnProperty('const')) {
    return schema.const;
  }

  if (Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
    return generateTemplateFromSchema(schema.oneOf[0]);
  }

  if (schema.hasOwnProperty('default')) {
    return schema.default;
  }

  if (Array.isArray(schema.examples) && schema.examples.length > 0) {
    return schema.examples[0];
  }

  switch (schema.type) {
    case 'object':
      const obj = {};
      if (schema.properties) {
        Object.keys(schema.properties).forEach((key) => {
          obj[key] = generateTemplateFromSchema(schema.properties[key]);
        });
      }
      return obj;

    case 'array':
      if (schema.items) {
        return [generateTemplateFromSchema(schema.items)];
      }
      return [];

    case 'string':
      if (schema.enum && schema.enum.length > 0) {
        return schema.enum[0];
      }
      if (schema.format === 'date') {
        return new Date().toISOString().substring(0, 10);
      }
      // yyyy-MM-ddThh:mm:ss.SSS
      if (
        schema.format ===
        '^[0-9]{4}-(0[1-9]|1[0-2])-[0-9]{2}T([01][0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9](\\.[0-9]{1,3})?)?$'
      ) {
        return new Date().toISOString().substring(0, 23);
      }
      // yyyy-MM-ddThh:mm:ss
      if (
        schema.format ===
        '^[0-9]{4}-(0[1-9]|1[0-2])-[0-9]{2}T([01][0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$'
      ) {
        return new Date().toISOString().substring(0, 19);
      }
      // yyyy-MM-ddThh:mm
      if (schema.format === '^[0-9]{4}-(0[1-9]|1[0-2])-[0-9]{2}T([01][0-9]|2[0-3]):[0-5][0-9]$') {
        return new Date().toISOString().substring(0, 16);
      }
      // yyyy-MM
      if (schema.format === '^[0-9]{4}-(0[1-9]|1[0-2])$') {
        return new Date().toISOString().substring(0, 7);
      }
      // yyyy-Www
      if (schema.format === '^[0-9]{4}-W(0[1-9]|[1-4][0-9]|5[0-3])$') {
        return `${new Date().toISOString().substring(0, 4)}-W01`;
      }
      // HH:mm:ss.SSS
      if (schema.format === '^([01][0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9](\\.[0-9]{1,3})?)?$') {
        return new Date().toISOString().substring(11, 23);
      }
      // HH:mm:ss
      if (schema.format === '^([01][0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$') {
        return new Date().toISOString().substring(11, 19);
      }
      // HH:mm
      if (schema.format === '^([01][0-9]|2[0-3]):[0-5][0-9]$') {
        return new Date().toISOString().substring(11, 16);
      }
      if (schema.format === '^#[0-9a-zA-Z]{6}$') {
        return '#ff00ff';
      }
      if (schema.format === 'tel') {
        return '123-456-7890';
      }
      if (schema.format === 'email') {
        return 'user@example.com';
      }
      return 'example_string';

    case 'number':
    case 'integer':
      if (schema.minimum !== undefined) return schema.minimum;
      return 0;

    case 'boolean':
      return false;

    case 'null':
      return null;

    default:
      return {};
  }
}

function waitForPageLoad(tabId) {
  return new Promise((resolve) => {
    let timeoutId;
    const done = () => {
      clearTimeout(timeoutId);
      chrome.tabs.onUpdated.removeListener(listener);
      resolve();
    };
    const listener = (updatedTabId, changeInfo) => {
      if (updatedTabId === tabId && changeInfo.status === 'complete') done();
    };

    timeoutId = setTimeout(done, 5000); // resolve rather than reject to avoid crashing the AI loop
    chrome.tabs.onUpdated.addListener(listener);

    // The tab may already be done loading, or gone; don't wait on the
    // timeout for those.
    chrome.tabs.get(tabId).then((tab) => {
      if (tab.status === 'complete') done();
    }).catch(done);
  });
}

document.querySelectorAll('.collapsible-header').forEach((header) => {
  header.addEventListener('click', () => {
    header.classList.toggle('collapsed');
    const content = header.nextElementSibling;
    if (content?.classList.contains('section-content')) {
      content.classList.toggle('is-hidden');
    }
  });
});
